meta_title: "Minerva Ballet"
meta_description: "Minerva Ballet is a new London based amateur adult ballet company with a fresh, professional approach. At Minerva Ballet we aim to bring our dancers from the studio to the stage. As adult dance students, you will have been taught ballet technique, you may even have become accustomed to a particular method or teacher. What none of this prepares you for is performance."
meta_image: "min.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@MinervaBallet"
