# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4e72a3111e0b53d06ad865c519f184be49131e6718238d7b023ccbf3cc4a3e33cfdf5acf850e99cefdc8da552db44217b229a90777f03431ef95fc52ed53a3

test:
  secret_key_base: efa6dd13fa6f86987349b9336e19b06e11d8f2d91251a0f73bbab8a64a498be99db9dc9d14eb545abca35a93ab99f1ea04bcbbf7dfe67e8b55656c3fcafb58a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
